#########################################################################################
###
### docker-compose file for egroupware-rocketchat package
###
### DO NOT CHANGE OR MODIFY THIS FILE!
###
### Place you modifications in /etc/egroupware-rocketchat/docker-compose.override.yml instead.
###
##########################################################################################
version: '3'
volumes:
  # store MongoDB on an (internal) Volume
  mongo:

services:
  rocketchat:
    image: quay.io/egroupware/rocket.chat:stable6
    command: >
      bash -c
        "for (( ; ; )); do
          node main.js &&
          s=$$? && break || s=$$?;
          echo \"Could not reach MongoDB. Waiting 5 secs ...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
    - /var/lib/egroupware/default/rocketchat/uploads:/app/uploads
    environment:
      - ROOT_URL=http://localhost/
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat?replicaSet=rs0&directConnection=true
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs0&directConnection=true
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:3000:3000
    container_name: rocketchat

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
     - mongo:/data/db
     - /var/lib/egroupware/default/rocketchat/dump:/dump
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    container_name: rocketchat-mongo

  # this container's job is just run the command to initialize the replica set.
  # it will run the command and remove himself (it will not stay running)
  mongo-init-replica:
    image: mongo:5.0
    command: >
      bash -c
        "for (( ; ; )); do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Could not reach MongoDB. Waiting 5 secs ...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongo