#########################################################################################
###
### Mail service for EGroupware
###
### DO NOT CHANGE OR MODIFY THIS FILE!
###
### Place you modifications in /etc/egroupware-mail/docker-compose.override.yml instead.
###
##########################################################################################

version: '3'
# we need access to networks of egroupware to be able to access the db, if running in a container
networks:
  egroupware-docker_default:
    external: true
volumes:
  # Postfix spool directory, so queued mail is not lost, when container is recreated or updated
  spool:
services:
  mail:
    restart: always
    networks:
      - egroupware-docker_default
    image: quay.io/egroupware/dovecot:lua
    container_name: egroupware-mail
    hostname: egroupware-mail
    ports:
      - "143:143"
      - "993:993"
      - "110:110"
      - "995:995"
      - "4190:4190"
      - "587:587"
      - "465:465"
    volumes:
      - /var/lib/egroupware-mail:/var/dovecot
      - $PWD/dovecot:/etc/dovecot
      - $PWD/certificate.pem:/etc/dovecot/certificate.pem
      - $PWD/certificate.key:/etc/dovecot/certificate.key
  smtp:
    restart: always
    networks:
      - egroupware-docker_default
    image: quay.io/egroupware/postfix:mysql
    container_name: egroupware-smtp
    hostname: egroupware-smtp
    ports:
      - "25:25"
    volumes:
      - spool:/var/spool/postfix
      - $PWD/postfix:/etc/postfix
      - $PWD/certificate.pem:/etc/postfix/certificate.pem
      - $PWD/certificate.key:/etc/postfix/certificate.key